apiVersion: v1
kind: Service
metadata:
  name: nginx2-service
spec:
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: 8080 # Port which this service will be listing to
      targetPort: 80 # Nginx deployment container port

